package ohos_app_cangjie_entry.app.prgghale.roomdb.theme

public let Blue10: Int64 = 0x000F5E
public let Blue20: Int64 = 0x001E92
public let Blue30: Int64 = 0x002ECC
public let Blue40: Int64 = 0x1546F6
public let Blue80: Int64 = 0xB8C3FF
public let Blue90: Int64 = 0xDDE1FF

public let DarkBlue10: Int64 = 0x00036B
public let DarkBlue20: Int64 = 0x000BA6
public let DarkBlue30: Int64 = 0x1026D3
public let DarkBlue40: Int64 = 0x3648EA
public let DarkBlue80: Int64 = 0xBBC2FF
public let DarkBlue90: Int64 = 0xDEE0FF

public let Yellow10: Int64 = 0x261900
public let Yellow20: Int64 = 0x402D00
public let Yellow30: Int64 = 0x5C4200
public let Yellow40: Int64 = 0x7A5900
public let Yellow80: Int64 = 0xFABD1B
public let Yellow90: Int64 = 0xFFDE9C

public let Red10: Int64 = 0x410001
public let Red20: Int64 = 0x680003
public let Red30: Int64 = 0x930006
public let Red40: Int64 = 0xBA1B1B
public let Red80: Int64 = 0xFFB4A9
public let Red90: Int64 = 0xFFDAD4

public let Grey10: Int64 = 0x191C1D
public let Grey20: Int64 = 0x2D3132
public let Grey80: Int64 = 0xC4C7C7
public let Grey90: Int64 = 0xE0E3E3
public let Grey95: Int64 = 0xEFF1F1
public let Grey99: Int64 = 0xFBFDFD

public let BlueGrey30: Int64 = 0x45464F
public let BlueGrey50: Int64 = 0x767680
public let BlueGrey60: Int64 = 0x90909A
public let BlueGrey80: Int64 = 0xC6C5D0
public let BlueGrey90: Int64 = 0xE2E1EC

public let SurfaceColor: Int64 = Grey99
